[2022-02-13 00:00:15,705] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-02-12T00:00:00+00:00 [queued]>
[2022-02-13 00:00:15,756] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-02-12T00:00:00+00:00 [queued]>
[2022-02-13 00:00:15,757] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-13 00:00:15,757] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-13 00:00:15,757] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-13 00:00:15,804] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): inaccurate> on 2022-02-12 00:00:00+00:00
[2022-02-13 00:00:15,817] {standard_task_runner.py:52} INFO - Started process 1352 to run task
[2022-02-13 00:00:15,823] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-02-12T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpiyao9c2y', '--error-file', '/tmp/tmpfn3ded0u']
[2022-02-13 00:00:15,824] {standard_task_runner.py:77} INFO - Job 20: Subtask inaccurate
[2022-02-13 00:00:16,051] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-02-12T00:00:00+00:00 [running]> on host f9b316006a9e
[2022-02-13 00:00:16,341] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-12T00:00:00+00:00
[2022-02-13 00:00:16,352] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-13 00:00:16,360] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-02-13 00:00:16,407] {subprocess.py:85} INFO - Output:
[2022-02-13 00:00:16,443] {subprocess.py:89} INFO - inaccurate
[2022-02-13 00:00:16,447] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-13 00:00:16,515] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220212T000000, start_date=20220213T000015, end_date=20220213T000016
[2022-02-13 00:00:16,617] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-13 00:00:16,714] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
